services:
  backend:
    build: ./backend
    ports:
      - "2000:2000" # exposing port 2000 for backend
    volumes:
      - ./backend:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm run dev # Runs backend in dev mode

  frontend:
    build: ./scheduler # use Dockerfile located in directory for build
    ports:
      - "3000:3000"
    volumes:
      - ./scheduler:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # To ensure changes are reflected for React
